[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[package]
name = "evaopt-core"
version = "0.1.0"
edition = "2021"
authors = ["EvaOpt Team"]
description = "High-performance LLM optimization engine core"

[lib]
name = "evaopt_core"
crate-type = ["cdylib", "rlib"]

[dependencies]
# 基礎功能
tokio = { version = "1.36", features = ["full"] }
anyhow = "1.0"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# 數值計算和優化
ndarray = { version = "0.15", features = ["serde"] }
half = { version = "2.3", features = ["num-traits"] }
rand = "0.8"
rayon = "1.8"

# Python 綁定
pyo3 = { version = "0.20", features = ["extension-module", "abi3-py37"] }
numpy = "0.20"

[build-dependencies]
pyo3-build-config = "0.20"
